INSERT INTO T_PERSON (ID,FIRST_NAME,LAST_NAME) VALUE (T_PERSON_SEQUENCE.NEXTVAL,'John', 'Doe');

INSERT INTO T_PERSON (ID,FIRST_NAME,LAST_NAME) VALUE (T_PERSON_SEQUENCE.NEXTVAL,'KAMGO', 'Romeo');

INSERT INTO T_PERSON (ID,FIRST_NAME,LAST_NAME) VALUE (T_PERSON_SEQUENCE.NEXTVAL,'Chetchom', 'Landry');
