CREATE SEQUENCE PUBLIC.T_PERSON_SEQUENCE START WITH 1;

CREATE CACHED TABLE PUBLIC.T_PERSON(
	ID BIGIN NOT NULL,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255)
	
);
ALTER TABLE PUBLIC.T_PERSON ADD CONSTRAINT PUBLIC.CONSTRAINT_PERSON_PK_PRIMARY KEY(ID);